### ISSUE TITLE
Pagamento Cartão Débito

### ISSUE THREAD

**Issue by clebertorrent** [jetdev/JetDev.Cielo#4]
Não estou conseguindo utilizar a dll para pagamento com Cartao de Debito, a transação só fica com Status de Criada, alguem poderia ajudar ?

**Comment by davaug2** [comment]
Quando você faz a solicitação para cartão de débito, é retornada a url de autenticação. Essa é a url quer irá direcionar o usuário para o banco emissor do cartão. Você deve direcionar o usuário para ela, para que ele autentique a transação. 

Após a autentique a situação da transação é alterada.

**Comment by ivanteles** [comment]
Quanto a função débito da cielo é muuuuuuito complicado funcionar, segue reposta recebida da cielo:

A autenticação é um processo solicitado pelo emissor do cartão, essa regra de solicitar autenticação ou não é especifica de cada emissor, podendo cartões do mesmo banco autenticar ou não as transações.
Os bancos que aceitam Visa Electron são: Banco Bradesco, Banco do Brasil, Santander, HSBC, Itaú, Mercantil, Sicredi, Banco de Brasília, Banco da Amazônia, Banco Espírito Santo e Banco do Nordeste. Para Maestro os bancos são: Banco do Brasil, Banco Santander, Banco de Brasília e Bancoob.
Caso o cartão seja de um destes bancos, o titular deve entrar em contato com o banco e verificar o motivo da negativa. Como o senhor informa que o direcionamento ao banco não ocorre, deve ser verificado junto ao banco qual o motivo (o cartão não tem autenticação?; é bloqueado para compras não presenciais?; o internet banking está com erro?; etc.)

**Comment by clebertorrent** [comment]
Mas vc teria um exemplo disto ? Pois ja tentei de todas as formas
Em 07/04/2016 01:18, "David Silva" notifications@github.com escreveu:

**Comment by davaug2** [comment]
Como descrito pelo @ivanteles, tem diversos entraves no uso de cartão de débito, a Cielo não consegue garantir que as transações podem ser autenticadas. Meu cartão de débito do Itaú, por exemplo, não funciona a autenticação. Direciona para o banco e mostra a mensagem para entrar em contato com o banco. 
Em um cenário de compra por impulso, você pode perder a conversão da venda nesse caso.
Pra resolver parte desse problema, integrei meu sistema com o Shopline do Itaú, assim os clientes do Itaú conseguem transferir pelo bankline para conta da minha empresa ou emitir boleto online. Mas só está resolvido para o Itaú. Esse é um bom nicho de mercado para ser explorado.
