### ISSUE TITLE
Versão da integração

### ISSUE THREAD

**Issue by vitoravale** [jetdev/JetDev.Cielo#5]
Gostaria de saber qual a versão de integração do Webservice está implementada neste pacote.

Se seria a mesma disponível em: [Integração Webservice 1.5](https://developercielo.github.io/Webservice-1.5/)

**Comment by ivanteles** [comment]
Sim. essa mesmo!

Atenciosamente.
_Ivan Teles_ (Analista de Sistemas/Desenvolvimento)
_Microsoft Certified Professional_
(61) 3710-2676 (Fixo) / (61) 8406-9719 (Tim) / (61) 9345-8963 (Claro)
Gtalk/Email: ivan@idevweb.com.br
Skype: idev.web

www.idevweb.com.br (Microsoft Partner)

Esta mensagem, incluindo seus anexos, tem caráter confidencial e seu
conteúdo é restrito aos seus destinatários.

Qualquer acesso, replicação ou disseminação desta mensagem ou parte dela,
sem autorização prévia do remetente ou do destinatário, é expressamente
proibida e configura ofensa ao inciso XII do Artigo 5º da Constituição
Federal. A iDev Web se responsabiliza apenas por documentos que contenham a
assinatura de um dos seus diretores. Os demais documentos têm fim
exclusivamente informativo.

2016-04-21 16:38 GMT-03:00 Vitor A. Vale notifications@github.com:

**Comment by vitoravale** [comment]
Obrigado
