### ISSUE TITLE
Falha em new Requisicoes.RequisicaoConsulta(transacaoId)

### ISSUE THREAD

**Issue by vitoravale** [jetdev/JetDev.Cielo#6]
Detectei que ao realizar a busca pela situação da transação e informar o TID no método _ObterSituacao_ mesmo não é recuperado disparando a exceção **ID da transação é obrigatório**, como pode ser visto nas imagens abaixo.

O problema ocorre quando o TID é informado ao construtor do _RequisicaoConsulta_
![tid1](https://cloud.githubusercontent.com/assets/4126824/14801624/1e9bc85a-0b21-11e6-975a-857a4be03c9b.png)

sendo necessário necessário informar o TID somente após a construção do objeto para o correto funcionamento
![tid2](https://cloud.githubusercontent.com/assets/4126824/14801733/ff245e50-0b21-11e6-9868-bb668254af0d.png)

**Comment by davaug2** [comment]
@vitoravale, você está utilizando a versão que está disponível no Nuget, estou correto? 

Se sim, enviei agora a versão 2.0.2 que tem diversos ajustes, incluindo a correção que você espera e inclusão da integração com o novo checkout da cielo. 

> Que não é tão novo assim

Peço que teste e se estiver corrigido, favor feche esta questão. 
[https://www.nuget.org/packages/JetDev.Cielo/2.0.2](url)

> Fique a vontade em contribuir.

**Comment by vitoravale** [comment]
Obrigado, agora está indo corretamente ao passar o tid diretamente
